### PR TITLE
Added framework.html in public folder

### PR DESCRIPTION
**Pull request by Aaliya7516**
This PR concerns with issue #3
Content and User Interface are placeholder for now. 
And will be changed according to our need.
@pixan198 please review

### CODE REVIEW

**Review by ashish11chawda — CHANGES_REQUESTED** [review]
- please remove style attributes from all html elements and create a class for those styles you need
- Remove CSS from html file and keep that CSS in a seperate file inside css folder

**Comment by Aaliya7516** [comment]
Sure, I will change it.

**Comment by Aaliya7516** [comment]
Separated CSS and HTML part of the code.
@pixan198 @suvansh-rana  please review.

**Comment by ashish11chawda** [comment]
@Aaliya7516 it looks good to me!

**Review by suvnshr — APPROVED** [review]

**Review by ashish11chawda — APPROVED** [review]

**Pull request merged**
