### PR TITLE
Implement Static Contributors Page

### PR DESCRIPTION
**Pull request by ashish11chawda**
This PR refers to the issue number #4 

The Preview can be viewed [here](https://community-website-1.ashishchawda.repl.co/public/contributors.html)

Only those Contributors have been added who've added them to [CONTRIBUTORS.md](https://github.com/we-developers-community/community-website/blob/master/CONTRIBUTORS.md) as per #8

### CODE REVIEW

**Review by suvnshr — APPROVED** [review]
Looks great, you can also try changing the font color of card titles to white, the shade of blue used currently is a little bright

**Comment by ashish11chawda** [comment]
@suvansh-rana Yeah, I'll Change it

**Review by deepaksy — APPROVED** [review]

**Review by pranjalbareth — APPROVED** [review]
Looks Great !! Awesome work ❤️🎉🎉

**Comment by Kamleshja** [comment]
Great work @pixan198

**Review by Kamleshja — APPROVED** [review]

**Comment by Aaliya7516** [comment]
Nice work 🎉

**Review by Aaliya7516 — APPROVED** [review]

**Comment by suvnshr** [comment]
@pixan198 looking good 👍

**Pull request merged**
